version: '3'

services:

  eshopwcfservice:
    image: eshop/wcfservice
    build:
      context: ./eShopWCFService
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-windows-developer