version: '3.4'

services:
  eshop.modernized.webforms:
    image: eshop/modernizedwebforms:dev
    container_name: eShopModernizedWebForms
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "eShopModernizedWebForms"
    volumes:
      - C:\dev\eShopModernizing\eShopModernizedWebFormsSolution\src\eShopModernizedWebForms:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

